version: '3.8'

services:
  mongodb-test:
    image: mongo:latest
    container_name: mongodb-test
    ports:
      - "27019:27017"
    networks:
      - test-network

  backend-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-test
    environment:
      - MONGODB_URL=mongodb://mongodb-test:27017
      - DATABASE_NAME=test_db
      - PYTHONPATH=.
    depends_on:
      - mongodb-test
    command: ["pytest", "tests"]
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
