[deploy]
startCommand = "uvicorn src.main:app --host 0.0.0.0 --port $PORT --workers ${UVICORN_WORKERS:-1} --proxy-headers --forwarded-allow-ips='*' --no-server-header"
healthcheckPath = "/api/v1/health/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
